name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install libssl-dev pkg-config libclang-dev -y
      - name: Publish
        run: |
          cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
          cd multiaddr && cargo publish
          cd ../secio && cargo publish
          cd ../yamux && cargo publish
          cd ../tentacle && cargo publish
