name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release:
  runs-on: ubuntu-latest
  include:
    - rust: stable
  steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get update && sudo apt-get install libssl-dev pkg-config libclang-dev -y
    - name: Publish
      run: |
        cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
        cd multiaddr && cargo publish --dry-run
        cd secio && cargo publish --dry-run
        cd yamux && cargo publish --dry-run
        cd tentacle && cargo publish --dry-run
